name = input("Please input your name:")
gender = input("Please input your gender:")
address = input("Please input your address:")
telephone = input("Please input your telephone number:")
cellphone = input("Please input your cellphone number:")
birthday = input("Please input your birthday:")
civil_status = input("Please input your civil status:")
birth_place = input("Please input your birth place:")
citizenship = input("Please input your citizenship:")
height = input("Please input your height:")
weight = input("Please input your weight:")
religion = input("Please input your religion:")
occupation = input("Please input your occupation:")
language = input("Please input languages that you speak:")

elementary = input("Please input your school in Elementary:")
elemgrad = input("When did you graduate?:")
high_school = input("Please input your school in High School:")
hsgrad = input("When did you graduate?:")
college = input("Please your school in College:")
collegegrad = input("When did you graduate?:")
degree = input("Please input the degree/s you achieved:")

company = input("Please input your company name:")
position = input("Please input your position:")
companyfrom = input("When did you start:")
companyto = input("When did you leave:")

charrefname = input("Please input the name of your characther reference:")
charcompany = input("Please input his/her company:")
charposition = input("Please input his/her position:")
charcontact = input("Please input his/her number:")

print("")
print("\t\t\t\t\t\t-----BIODATA-----")
print(" ")
print("PERSONAL INFORMATION")
print("")
print("Name: "+name)
print("Gender: "+gender)
print("Address: "+address)
print("Telephone number: "+telephone)
print("Cellphone: "+cellphone)
print("Birthday: "+birthday)
print("Civil Status: "+civil_status)
print("Place of Birth: "+birth_place)
print("Citizenship: "+citizenship)
print("Height: "+height)
print("Weight: "+weight)
print("Religion: "+religion)
print("Occupation: "+occupation)
print("Languages or dialect spoken or written: " +language)

print("")
print("EDUCATIONAL BACKGROUND")
print("")
print("Elementary: "+elementary)
print("Year graduated: "+elemgrad)
print("")
print("High School: "+high_school)
print("Year graduated: "+hsgrad)
print("")
print("College: "+college)
print("Year graduated: "+collegegrad)
print("Degree achieved: "+degree)

print("")
print("EMPLOYMENT RECORD")
print("")
print("Company: "+company)
print("Position: "+position)
print("From: "+companyfrom)
print("To: "+companyto)

print("")
print("CHARACTHER REFERENCE")
print("")
print("Name: "+charrefname)
print("Company: "+charcompany)
print("Position: "+charposition)
print("Number: "+charcontact)

